# Generated by Django 3.1 on 2021-03-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201219_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Canceled')], default=1),
        ),
    ]
